### ISSUE TITLE
Does not parse correctly with localhost

### ISSUE THREAD

**Issue by nadiasvertex** [sporto/erl#1]
> a = "http://localhost:7000/override.html?queue=wtlib&package=test.pkg"
> 
> Erl.parse a
> { host = [""], fragment = [], password = "", path = ["localhost:7000","override.html"], port$ = 7000, protocol = "http", query = Dict.fromList [("package","test.pkg"),("queue","wtlib")], username = "" }
> 
> Erl.toString <| Erl.parse a
> "http://:7000/localhost%3A7000/override.html?package=test.pkg&queue=wtlib" : String

**Comment by sporto** [comment]
Thanks. Fixed in `4.1.1`
