### ISSUE TITLE
Query should not be a Dict String String

### ISSUE THREAD

**Issue by francisdb** [sporto/erl#16]
Since url query parameters can appear multiple times representing them as `Dict String String` would only keep one of the values

2 options

`List ( String, String )` or `Dict String (List String)`

the first option also keeps ordering, not sure what the spec says about that

**Comment by sporto** [comment]
Agree, not sure what the best option is, both seem to have pros and cons. I can see `List ( String, String )` probably easier to work with from a parsing perspective. But maybe the Dict can be more useful for users?

**Comment by francisdb** [comment]
There's even discussion on the duplicate parameter values order :-) 
http://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys

Maybe something to do a poll for on the slack channel?

**Comment by sporto** [comment]
Done in `11.0.0`, the query is now a `List (String, String)`

**Comment by francisdb** [comment]
great, thanks
