### ISSUE TITLE
Does not parse hostnames without TLD

### ISSUE THREAD

**Issue by chendrix** [sporto/erl#17]
Comes from concourse/concourse#780

When using Erl to parse the URL "http://devvm-concourse:8080", Erl parses "devvm-concourse" as the Path instead of the Hostname.

**Comment by sporto** [comment]
Yes, Erl won't parse this correctly as there is not TLD. The only exception built in is `localhost`.
Do you need to use this host name? Can you add something e.g. `devvm-concourse.local`?

**Comment by chendrix** [comment]
But URLs don't need to have a TLD. A hostname can be resolved in a bunch of ways, only one of which is DNS.

https://en.m.wikipedia.org/wiki/Hostname

I would also reference the RFC for URIs to get the reference implementation correct: https://tools.ietf.org/html/rfc3986

**Comment by sporto** [comment]
Fixed by https://github.com/sporto/erl/pull/18

**Comment by sporto** [comment]
Published 11.1.1

**Comment by chendrix** [comment]
Thanks so much

@sporto would it be possible to back port this fix to your 10.0 series for elm 0.17? That would be really greatly appreciated!

**Comment by sporto** [comment]
@chendrix 	I don't think there is a way to do that with the Elm package manager. It won't let me publish an older version. I will ask around.

I think you might need to copy the source code to do this. Any other ideas?

**Comment by chendrix** [comment]
I actually asked in the elm slack and user "fredcy" said they were able to successfully publish a patch to an old version, even for an Elm 0.17 package.

https://elmlang.slack.com/archives/general/p1483656345010824

Looks like it's possible, but I'm with you @sporto I've never done it before 😨
