### ISSUE TITLE
Expose queryComponent in the module

### ISSUE THREAD

**Issue by AdrianRibao** [sporto/erl#4]
Do you think it's a good idea to expose the queryComponent (and perhaps all the other components) in the module?

I think it could be very useful. I had a situation where the only thing I needed was the query string but I couldn't get it.

**Comment by sporto** [comment]
Yes this sounds useful, not sure about the name `queryComponent` for the function

**Comment by AdrianRibao** [comment]
I think the name is ok.

BTW, great new things in v7. I like that the query is removed when there is an empty value, I was taking care of that in my code and now the library do it for me. Great!

**Comment by sporto** [comment]
7.2 adds `queryToString`, which is equivalent to `queryComponent`

**Comment by AdrianRibao** [comment]
Great thanks!
